# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boidwatch < Formula
  desc "Public HTTPS-only CLI for Boidwatch — drive synthetic-agent runs from the terminal or an LLM agent harness."
  homepage "https://boidwatch.com"
  version "1.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boidwatch/cli/releases/download/v1.0.0/boidwatch_1.0.0_darwin_x86_64.tar.gz"
      sha256 "13c810c5df6639d56196daf5fe145f174824b0236d0455188134e6656a7d9027"

      define_method(:install) do
        bin.install "boidwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boidwatch/cli/releases/download/v1.0.0/boidwatch_1.0.0_darwin_arm64.tar.gz"
      sha256 "ea3bfdb1b2cfb6c3bd75fe52469322183c8f72d6afe441f1ad2c094a3053c454"

      define_method(:install) do
        bin.install "boidwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boidwatch/cli/releases/download/v1.0.0/boidwatch_1.0.0_linux_x86_64.tar.gz"
      sha256 "96c22ffa3eb352f939048462ef3dbc8161cc9d232b03d891d1dc0c46c6306ba7"
      define_method(:install) do
        bin.install "boidwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boidwatch/cli/releases/download/v1.0.0/boidwatch_1.0.0_linux_arm64.tar.gz"
      sha256 "0d8bea2dd087aeded5acaf6c61a69962654576f6ccb52ebe0eda91f5843b4383"
      define_method(:install) do
        bin.install "boidwatch"
      end
    end
  end

  test do
    system "#{bin}/boidwatch", "version"
  end
end
