# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boidwatch < Formula
  desc "Public HTTPS-only CLI for Boidwatch — drive synthetic-agent runs from the terminal or an LLM agent harness."
  homepage "https://boidwatch.com"
  version "1.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boidwatch/cli/releases/download/v1.1.0/boidwatch_1.1.0_darwin_x86_64.tar.gz"
      sha256 "9ff4ab839720a0e4ef7c4c8f84ccbf0e773839828b87fa37adc5c7944d601f1d"

      define_method(:install) do
        bin.install "boidwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boidwatch/cli/releases/download/v1.1.0/boidwatch_1.1.0_darwin_arm64.tar.gz"
      sha256 "d22ac0f57828240d2d6c3f6c957f145bdb62c13400b7980a1c508c73bdf82852"

      define_method(:install) do
        bin.install "boidwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boidwatch/cli/releases/download/v1.1.0/boidwatch_1.1.0_linux_x86_64.tar.gz"
      sha256 "f7abaf416be8fc98070875d69ef753c918a85daec7c5b3a5aaf157a02a43975a"
      define_method(:install) do
        bin.install "boidwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boidwatch/cli/releases/download/v1.1.0/boidwatch_1.1.0_linux_arm64.tar.gz"
      sha256 "797ba5fe9416541b56e0c3ffe07ef1198f6c50f525a14a3714ac68fe13116c29"
      define_method(:install) do
        bin.install "boidwatch"
      end
    end
  end

  test do
    system "#{bin}/boidwatch", "version"
  end
end
